local navigator = require('goto-path.navigator')
local parser = require('goto-path.parser')

describe("navigator", function()
    describe("open_file", function()
        it("opens existing file", function()
            local parsed = parser.parse("README.md")
            navigator.open_file(parsed, {})
            local bufname = vim.api.nvim_buf_get_name(0)
            assert.truthy(bufname:match("README.md$"))
        end)

        it("opens file at specific line", function()
            local parsed = parser.parse("README.md:5")
            navigator.open_file(parsed, {})
            local pos = vim.api.nvim_win_get_cursor(0)
            assert.are.equal(5, pos[1])
        end)

        it("opens file at specific line and column", function()
            local parsed = parser.parse("README.md:3:10")
            navigator.open_file(parsed, {})
            local pos = vim.api.nvim_win_get_cursor(0)
            assert.are.equal(3, pos[1])
            assert.are.equal(9, pos[2])
        end)

        it("handles path with directory", function()
            local parsed = parser.parse("Makefile")
            navigator.open_file(parsed, {})
            local bufname = vim.api.nvim_buf_get_name(0)
            assert.truthy(bufname:match("Makefile$"))
        end)

        it("uses prefix_paths to find files", function()
            local parsed = parser.parse("testfile.txt")
            navigator.open_file(parsed, { prefix_paths = { "test/" } })
            local bufname = vim.api.nvim_buf_get_name(0)
            assert.truthy(bufname:match("testfile.txt$"))
        end)
    end)
end)
