local parser = require('goto-path.parser')

describe("parser", function()
    describe("parse", function()
        it("parses simple filename", function()
            local result = parser.parse("init.lua")
            assert.are.equal("", result.path)
            assert.are.equal("init.lua", result.file_name)
            assert.are.equal(1, result.row)
            assert.are.equal(0, result.column)
        end)

        it("parses filename with line number", function()
            local result = parser.parse("init.lua:42")
            assert.are.equal("", result.path)
            assert.are.equal("init.lua", result.file_name)
            assert.are.equal(42, result.row)
            assert.are.equal(0, result.column)
        end)

        it("parses filename with line and column", function()
            local result = parser.parse("init.lua:42:10")
            assert.are.equal("", result.path)
            assert.are.equal("init.lua", result.file_name)
            assert.are.equal(42, result.row)
            assert.are.equal(10, result.column)
        end)

        it("extracts text from double quotes", function()
            local result = parser.parse('"init.lua"')
            assert.are.equal("", result.path)
            assert.are.equal("init.lua", result.file_name)
            assert.are.equal(1, result.row)
            assert.are.equal(0, result.column)
        end)

        it("extracts text from partial quotes", function()
            local result = parser.parse('"init.lua')
            assert.are.equal("", result.path)
            assert.are.equal("init.lua", result.file_name)
            assert.are.equal(1, result.row)
            assert.are.equal(0, result.column)
        end)

        it("extracts text from angle brackets", function()
            local result = parser.parse('<init.lua>')
            assert.are.equal("", result.path)
            assert.are.equal("init.lua", result.file_name)
            assert.are.equal(1, result.row)
            assert.are.equal(0, result.column)
        end)

        it("extracts text from square brackets", function()
            local result = parser.parse('[init.lua]')
            assert.are.equal("", result.path)
            assert.are.equal("init.lua", result.file_name)
            assert.are.equal(1, result.row)
            assert.are.equal(0, result.column)
        end)

        it("extracts text from parentheses", function()
            local result = parser.parse('(init.lua)')
            assert.are.equal("", result.path)
            assert.are.equal("init.lua", result.file_name)
            assert.are.equal(1, result.row)
            assert.are.equal(0, result.column)
        end)

        it("replaces environment variables", function()
            vim.fn.setenv("TEST_VAR", "/test/path")
            local result = parser.parse("$(TEST_VAR)/file.lua")
            assert.are.equal("/test/path", result.path)
            assert.are.equal("file.lua", result.file_name)
            assert.are.equal(1, result.row)
            assert.are.equal(0, result.column)
        end)

        it("handles path with directories", function()
            local result = parser.parse("/path/to/init.lua:42:10")
            assert.are.equal("/path/to", result.path)
            assert.are.equal("init.lua", result.file_name)
            assert.are.equal(42, result.row)
            assert.are.equal(10, result.column)
        end)

        it("extracts file name from path", function()
            local result = parser.parse("/path/to/file.lua")
            assert.are.equal("/path/to", result.path)
            assert.are.equal("file.lua", result.file_name)
            assert.are.equal(1, result.row)
            assert.are.equal(0, result.column)
        end)

        it("handles trailing colon", function()
            local result = parser.parse("init.lua:42:")
            assert.are.equal("", result.path)
            assert.are.equal("init.lua", result.file_name)
            assert.are.equal(42, result.row)
            assert.are.equal(0, result.column)
        end)

        it("handles trailing colon with column", function()
            local result = parser.parse("init.lua:42:10:")
            assert.are.equal("", result.path)
            assert.are.equal("init.lua", result.file_name)
            assert.are.equal(42, result.row)
            assert.are.equal(10, result.column)
        end)
    end)
end)
